name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name mohamedaymanacr

      - name: Build image
        run: |
          docker build -t mohamedaymanacr.azurecr.io/resume-backend:${{ github.event.workflow_run.head_sha }} .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: mohamedaymanacr.azurecr.io/resume-backend:${{ github.event.workflow_run.head_sha }}
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL
          ignore-unfixed: true

      - name: Push image
        run: |
          docker push mohamedaymanacr.azurecr.io/resume-backend:${{ github.event.workflow_run.head_sha }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: resume-aks

      - name: Update deployment image
        run: |
          kubectl set image deployment/backend \
            backend=mohamedaymanacr.azurecr.io/resume-backend:${{ github.event.workflow_run.head_sha }} \
            -n resume

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/backend -n resume
